<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="hlHomePage.aspx.cs" Inherits="WebApplication1.WebForm3" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
   <style>
       
       html {
        scroll-behavior: smooth;
        
       }
         .fix-top {
  position: fixed;
  width: 100%;
  top: 0px;
  left: 0px;
}

   </style>
</head>
<body>
    
    <form id="form1" runat="server">
    <div style="background-color:blueviolet;" class="fix-top">
        
    <asp:HyperLink ID="hlImage" NavigateUrl="~/ChooseList.aspx"  runat="server"><asp:Image ID="imgClick" runat="server" ImageUrl="~/Images/DUlogo.svg"/></asp:HyperLink>
        
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        
        <asp:HyperLink id="hlHome" navigateurl="~/hlhomepage.aspx#Home"  runat="server" borderstyle="groove" forecolor="black">Home</asp:HyperLink>&nbsp;&nbsp;<asp:HyperLink id="hlMembers" navigateurl="~/hlhomepage.aspx#Members" runat="server" borderstyle="groove" forecolor="black">Members</asp:HyperLink>&nbsp;&nbsp;<asp:HyperLink id="hlFacilities" navigateurl="~/hlhomepage.aspx#Facilities" runat="server" borderstyle="groove" forecolor="black">Facilities</asp:HyperLink>&nbsp;&nbsp;<asp:HyperLink id="hlDepartment" navigateurl="~/hlhomepage.aspx#Departments" runat="server" borderstyle="groove" forecolor="black">Departments</asp:HyperLink>&nbsp;&nbsp;<asp:HyperLink id="hlAbout" navigateurl="~/hlhomepage.aspx#About" runat="server" borderstyle="groove" forecolor="black">About us</asp:HyperLink>&nbsp;&nbsp;<asp:HyperLink id="hlContact" navigateurl="~/hlhomepage.aspx#Contact" runat="server" borderstyle="groove" forecolor="black">Contact us</asp:HyperLink>
        </div>
   
        <h1 id="Home"><br/><br/>Darshan University</h1><p style="font-size: 30px; font-weight: normal; font-style: normal; font-variant: inherit; text-transform: capitalize; font-family: 'Bauhaus 93'; visibility: inherit; overflow: inherit; background-color: #CCCCFF; text-align: justify; white-space: normal; letter-spacing: 0em; word-spacing: 0.5em; background-attachment: scroll;" title="Home">The United States has the second-largest Gujarati diaspora after Pakistan. The highest concentration of the population of over 100,000 is in the New York City Metropolitan Area alone, notably in the growing Gujarati diasporic center of India Square in Jersey City, New Jersey, and Edison in Middlesex County in Central New Jersey. Significant immigration from India to the United States started after the landmark Immigration and Nationality Act of 1965.[72][73] Early immigrants after 1965 were highly educated professionals. Since US immigration laws allow sponsoring immigration of parents, children and particularly siblings on the basis of family reunion, the numbers rapidly swelled.[74] A number of Gujarati are twice or thrice-migrant because they came directly from the former British colonies of East Africa or from East Africa via Great Britain respectively[75] Given the Gujarati propensity for business enterprise, a number of them opened shops and motels. While they may make up only around 0.1% of the population in the United States, Gujarati Americans control over 40% of the hospitality market in the country, for a combined net worth of over US$40 billion and employing over one million employees.[76][77][78] Gujaratis, especially the Patidar samaj, also dominate as franchisees of fast food restaurant chains such as Subway and Dunkin' Donuts.[79] The descendants of the Gujarati immigrant generation have also made high levels of advancement into professional fields, including as physicians, engineers and politicians. In August 2016, Air India commenced single aircraft (no transfer) flight service between Ahmedabad and Newark Liberty International Airport in New Jersey, via London Heathrow International Airport.</p>
        <h1 id="Members"><br/><br/>Mambers</h1><p style="font-size: 30px; font-weight: normal; font-style: normal; font-variant: inherit; text-transform: capitalize; font-family: 'News706 BT'; visibility: inherit; overflow: inherit; background-color: #CCCCCC; text-align: justify; white-space: normal; letter-spacing: 0em; word-spacing: 0.5em;" title="About Darshan University Members">The United States has the second-largest Gujarati diaspora after Pakistan. The highest concentration of the population of over 100,000 is in the New York City Metropolitan Area alone, notably in the growing Gujarati diasporic center of India Square in Jersey City, New Jersey, and Edison in Middlesex County in Central New Jersey. Significant immigration from India to the United States started after the landmark Immigration and Nationality Act of 1965.[72][73] Early immigrants after 1965 were highly educated professionals. Since US immigration laws allow sponsoring immigration of parents, children and particularly siblings on the basis of family reunion, the numbers rapidly swelled.[74] A number of Gujarati are twice or thrice-migrant because they came directly from the former British colonies of East Africa or from East Africa via Great Britain respectively[75] Given the Gujarati propensity for business enterprise, a number of them opened shops and motels. While they may make up only around 0.1% of the population in the United States, Gujarati Americans control over 40% of the hospitality market in the country, for a combined net worth of over US$40 billion and employing over one million employees.[76][77][78] Gujaratis, especially the Patidar samaj, also dominate as franchisees of fast food restaurant chains such as Subway and Dunkin' Donuts.[79] The descendants of the Gujarati immigrant generation have also made high levels of advancement into professional fields, including as physicians, engineers and politicians. In August 2016, Air India commenced single aircraft (no transfer) flight service between Ahmedabad and Newark Liberty International Airport in New Jersey, via London Heathrow International Airport.</p>
        <h1 id="Facilities"><br/><br/>Facilities</h1><p style="font-size: 30px; font-weight: normal; font-style: normal; font-variant: inherit; text-transform: capitalize; font-family: Broadway; visibility: inherit; overflow: inherit; background-color: #CCFFFF; text-align: justify; white-space: normal; letter-spacing: 0em; word-spacing: 0.5em;" title="Facilities of Drashan University">The United States has the second-largest Gujarati diaspora after Pakistan. The highest concentration of the population of over 100,000 is in the New York City Metropolitan Area alone, notably in the growing Gujarati diasporic center of India Square in Jersey City, New Jersey, and Edison in Middlesex County in Central New Jersey. Significant immigration from India to the United States started after the landmark Immigration and Nationality Act of 1965.[72][73] Early immigrants after 1965 were highly educated professionals. Since US immigration laws allow sponsoring immigration of parents, children and particularly siblings on the basis of family reunion, the numbers rapidly swelled.[74] A number of Gujarati are twice or thrice-migrant because they came directly from the former British colonies of East Africa or from East Africa via Great Britain respectively[75] Given the Gujarati propensity for business enterprise, a number of them opened shops and motels. While they may make up only around 0.1% of the population in the United States, Gujarati Americans control over 40% of the hospitality market in the country, for a combined net worth of over US$40 billion and employing over one million employees.[76][77][78] Gujaratis, especially the Patidar samaj, also dominate as franchisees of fast food restaurant chains such as Subway and Dunkin' Donuts.[79] The descendants of the Gujarati immigrant generation have also made high levels of advancement into professional fields, including as physicians, engineers and politicians. In August 2016, Air India commenced single aircraft (no transfer) flight service between Ahmedabad and Newark Liberty International Airport in New Jersey, via London Heathrow International Airport.</p>
        <h1 id="Departments"><br/><br/>Departments</h1><p style="font-size: 30px; font-weight: normal; font-style: normal; font-variant: inherit; text-transform: capitalize; font-family: Algerian; visibility: inherit; overflow: inherit; background-color: #FFFFCC; text-align: justify; white-space: normal; letter-spacing: 0em; word-spacing: 0.5em;" title="Darshan University all departments">The United States has the second-largest Gujarati diaspora after Pakistan. The highest concentration of the population of over 100,000 is in the New York City Metropolitan Area alone, notably in the growing Gujarati diasporic center of India Square in Jersey City, New Jersey, and Edison in Middlesex County in Central New Jersey. Significant immigration from India to the United States started after the landmark Immigration and Nationality Act of 1965.[72][73] Early immigrants after 1965 were highly educated professionals. Since US immigration laws allow sponsoring immigration of parents, children and particularly siblings on the basis of family reunion, the numbers rapidly swelled.[74] A number of Gujarati are twice or thrice-migrant because they came directly from the former British colonies of East Africa or from East Africa via Great Britain respectively[75] Given the Gujarati propensity for business enterprise, a number of them opened shops and motels. While they may make up only around 0.1% of the population in the United States, Gujarati Americans control over 40% of the hospitality market in the country, for a combined net worth of over US$40 billion and employing over one million employees.[76][77][78] Gujaratis, especially the Patidar samaj, also dominate as franchisees of fast food restaurant chains such as Subway and Dunkin' Donuts.[79] The descendants of the Gujarati immigrant generation have also made high levels of advancement into professional fields, including as physicians, engineers and politicians. In August 2016, Air India commenced single aircraft (no transfer) flight service between Ahmedabad and Newark Liberty International Airport in New Jersey, via London Heathrow International Airport.</p>
        <h1 id="About"><br/><br/>About University</h1><p style="font-size: 30px; font-weight: normal; font-style: normal; font-variant: inherit; text-transform: capitalize; font-family: 'Colonna MT'; visibility: inherit; overflow: inherit; background-color: #BCD6C8; text-align: justify; white-space: normal; letter-spacing: 0em; word-spacing: 0.5em;" title="All about the Darshan University">The United States has the second-largest Gujarati diaspora after Pakistan. The highest concentration of the population of over 100,000 is in the New York City Metropolitan Area alone, notably in the growing Gujarati diasporic center of India Square in Jersey City, New Jersey, and Edison in Middlesex County in Central New Jersey. Significant immigration from India to the United States started after the landmark Immigration and Nationality Act of 1965.[72][73] Early immigrants after 1965 were highly educated professionals. Since US immigration laws allow sponsoring immigration of parents, children and particularly siblings on the basis of family reunion, the numbers rapidly swelled.[74] A number of Gujarati are twice or thrice-migrant because they came directly from the former British colonies of East Africa or from East Africa via Great Britain respectively[75] Given the Gujarati propensity for business enterprise, a number of them opened shops and motels. While they may make up only around 0.1% of the population in the United States, Gujarati Americans control over 40% of the hospitality market in the country, for a combined net worth of over US$40 billion and employing over one million employees.[76][77][78] Gujaratis, especially the Patidar samaj, also dominate as franchisees of fast food restaurant chains such as Subway and Dunkin' Donuts.[79] The descendants of the Gujarati immigrant generation have also made high levels of advancement into professional fields, including as physicians, engineers and politicians. In August 2016, Air India commenced single aircraft (no transfer) flight service between Ahmedabad and Newark Liberty International Airport in New Jersey, via London Heathrow International Airport.</p>
        <h1 id="Contact"><br/><br/>Contact Us</h1><p style="font-family: 'Eras Bold ITC'; font-size: 30px; background-color: #BBA5A4" title="For the contact the university">The United States has the second-largest Gujarati diaspora after Pakistan. The highest concentration of the population of over 100,000 is in the New York City Metropolitan Area alone, notably in the growing Gujarati diasporic center of India Square in Jersey City, New Jersey, and Edison in Middlesex County in Central New Jersey. Significant immigration from India to the United States started after the landmark Immigration and Nationality Act of 1965.[72][73] Early immigrants after 1965 were highly educated professionals. Since US immigration laws allow sponsoring immigration of parents, children and particularly siblings on the basis of family reunion, the numbers rapidly swelled.[74] A number of Gujarati are twice or thrice-migrant because they came directly from the former British colonies of East Africa or from East Africa via Great Britain respectively[75] Given the Gujarati propensity for business enterprise, a number of them opened shops and motels. While they may make up only around 0.1% of the population in the United States, Gujarati Americans control over 40% of the hospitality market in the country, for a combined net worth of over US$40 billion and employing over one million employees.[76][77][78] Gujaratis, especially the Patidar samaj, also dominate as franchisees of fast food restaurant chains such as Subway and Dunkin' Donuts.[79] The descendants of the Gujarati immigrant generation have also made high levels of advancement into professional fields, including as physicians, engineers and politicians. In August 2016, Air India commenced single aircraft (no transfer) flight service between Ahmedabad and Newark Liberty International Airport in New Jersey, via London Heathrow International Airport.</p>  
    </form>
</body>
</html>
